// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wykjmeusgqxwvvuwpnjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5a2ptZXVzZ3F4d3Z2dXdwbmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDc2MDcsImV4cCI6MjA3MTA4MzYwN30._Rk1XWvKoYq3RGbNn2tuHzBUFKhYBdTpB4QGjehRaHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});